{
 "title": "S6000",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "aceiot-svg-panel",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"S6000U_measurements\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Temperature & Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: -3h)\r\n  |> filter(fn: (r) => r._measurement == \"S6000U_measurements\")\r\n  |> filter(fn: (r) => r._field =~ /temperature/ or r._field =~ /humidity/)\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"S6000U_measurements\")\r\n  |> filter(fn: (r) => r._field =~ /humidity/)"
    }
   ]
  },
  {
   "title": "Sound Level",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: -3h)\r\n  |> filter(fn: (r) => r._measurement == \"S6000U_measurements\")\r\n  |> filter(fn: (r) => r._field =~ /noise/)\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "aceiot-svg-panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"S6000U_measurements\")\r\n  |> filter(fn: (r) => r._field == \"tof\")"
    }
   ]
  },
  {
   "title": "Tilt",
   "type": "aceiot-svg-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"S6000U_measurements\")\r\n  |> filter(fn: (r) => r._field == \"angle\" or r._field =~ /vibrAcc/)"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "hPa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"S6000U_measurements\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")"
    }
   ]
  }
 ]
}